# -*- coding: utf-8 -*-
"""temperature DAT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFpNQfYHzuTcJV4OLonywmb2rJkXySAV
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl

#Download Data https://www.kaggle.com/sevgisarac/temperature-change?select=Environment_Temperature_change_E_All_Data_NOFLAG.csv

temperature_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/project DAT borntodev/Environment_Temperature.csv", encoding = "ISO-8859-1")

temperature_df

temperature_10_year = temperature_df[temperature_df.columns[-10:]]
temperature_10_year

asia_temp = temperature_df[temperature_df["Area"] == "Asia"]
asia_temp

asia_temp_change = asia_temp[asia_temp["Element"] == "Temperature change"][:-5]
asia_temp_change

fig = plt.figure(figsize=(10,5))
ax = fig.subplots()

ax.set_title("58 years ASIA Temperature change")
ax.set_xlabel("Months")
ax.set_ylabel("Temperature change")
ax.legend()

asia_temp_change.plot(kind = "line", x = "Months", y = "Y1961", color = "Green", marker = "o", ax = ax)
asia_temp_change.plot(kind = "line", x = "Months", y = "Y2019", color = "Red", marker = "v", ax = ax)


fig.show()

antarctica_temp = temperature_df[temperature_df["Area"] == "Antarctica"]
antarctica_temp

antarctica_temp_change = antarctica_temp[antarctica_temp["Element"] == "Temperature change"][:-5]
antarctica_temp_change

fig = plt.figure(figsize=(10,5))
ax = fig.subplots()

ax.set_title("58 years ANTARCTICA Temperature change")
ax.set_xlabel("Months")
ax.set_ylabel("Temperature change")
ax.legend()

antarctica_temp_change.plot(kind = "line", x = "Months", y = "Y1961",color = "Black", marker = "o", ax = ax)
antarctica_temp_change.plot(kind = "line", x = "Months", y = "Y2019",color='blue', marker = "v", ax = ax)

fig.show()

fig = plt.figure(figsize=(10,5))
ax = fig.subplots()

ax.set_title("ASIA and ANTARCTICA Temperature change 2019")
ax.set_xlabel("Months")
ax.set_ylabel("Temperature change")
ax.legend()

asia_temp_change.plot(kind = "line", x = "Months", y = "Y2019" ,color = "Red", marker = "s", ax = ax, label = "ASIA")
antarctica_temp_change.plot(kind = "line", x = "Months", y = "Y2019",color = "Blue", marker = "x", ax = ax, label = "ANTARCTICA")

fig.show()

thailand_temp = temperature_df[temperature_df["Area"] == "Thailand"]
thailand_temp_change = thailand_temp[thailand_temp["Element"] == "Temperature change"][:-5]
thailand_temp_change

fig = plt.figure(figsize=(10,5))
ax = fig.subplots()

ax.set_title("Thailand Temperature change")
ax.set_xlabel("Months")
ax.set_ylabel("Temperature change")
ax.legend()

thailand_temp_change.plot(kind = "line", x = "Months", y = "Y2000" ,color = "Red", marker = "s", ax = ax)
thailand_temp_change.plot(kind = "line", x = "Months", y = "Y2019",color = "Blue", marker = "x", ax = ax)

fig.show()